apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-login
spec:
  selector:
    matchLabels:
      app: todo-login
  template:
    metadata:
      labels:
        app: todo-login
    spec:
      containers:
      - name: todo-login
        image: todologin
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: loginpage
spec:
  selector:
    app: todo-login
  ports:
  - port: 8081
    targetPort: 8081
  type: LoadBalancer

